### ISSUE TITLE
writetable permission issue

### ISSUE THREAD

**Issue by nickua** [djocker/orocrm#4]
Once I run command 
`docker-compose -f docker-compose-auto.yml up` or `docker-compose -f docker-compose.yml up` and then go to http://localhost:3080/ it shows error 'app/import_export/ directory must be writable'

**Comment by SergeyCherepanov** [comment]
Hi @nickua, this issue appeared after the latest release. I need some time to fix it.

**Comment by SergeyCherepanov** [comment]
Fixed by https://github.com/djocker/oromono/commit/cca6e5b518ba2770bed1f65e49561e3486bf552e
